language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t guruprasadlakkond/docker-react-app -f dockerfile.dev .

script:
    - docker run -e CI=true guruprasadlakkond/docker-react-app npm run test -- --coverage 